//! Stable infrastructure failures exposed above the reusable executor.
//!
//! Executor internals deliberately accept type-erased state, capture, prepared-
//! code, and precompile providers. Their arbitrary errors are normalized to
//! `InfrastructureFailure`; native executor failures keep their useful names.

pub const Error = error{
    InfrastructureFailure,
    OutOfMemory,

    AccessCapacityTooLarge,
    AccountCapacityExceeded,
    CodeCacheByteCapacityExceeded,
    CodeCacheEntryCapacityExceeded,
    CreatedContractCapacityExceeded,
    DeletedAccountCapacityExceeded,
    DirtyAccountCapacityExceeded,
    FrameCapacityExceeded,
    FrameIoCapacityExceeded,
    JournalCapacityExceeded,
    LogCapacityExceeded,
    LogDataCapacityExceeded,
    LogTopicCapacityExceeded,
    OriginalStorageCapacityExceeded,
    PreparedCodeCapacityExceeded,
    ResultOutputCapacityExceeded,
    SelfdestructCapacityExceeded,
    StateCapacityTooLarge,
    StorageOverlayCapacityExceeded,
    TraceCapacityExceeded,
    TraceIndexOverflow,
    TransientStorageCapacityExceeded,
    TransientStorageCapacityTooLarge,
    WarmAccountCapacityExceeded,
    WarmStorageCapacityExceeded,

    ActiveAccessState,
    ActiveCaptureFrames,
    ActiveCheckpoints,
    ActiveExecutionCheckpoints,
    ActiveFramesInFrameStore,
    ActiveJournal,
    ActiveLogs,
    ActivePreparedCodeExecution,
    ActiveRuntimeFrames,
    ActiveStateOverlay,
    ActiveTransactionScope,
    ActiveTransientStorage,
    BlockExecutionActive,
    BlockExecutionFinished,
    CaptureOperationActive,
    CaptureOperationNotActive,
    CheckpointClosed,
    CheckpointIdExhausted,
    CheckpointOrderViolation,
    ExecutedTransactionActive,
    ExecutionContextMismatch,
    ExecutionScopeRootMismatch,
    MissingPreparedCodeExecution,
    MissingTransactionScope,
    MissingTxContext,
    NoCurrentTransaction,
    PendingTransactionActive,
    RuntimeResourcesLocked,
    StaleBlockExecution,
    StaleTransactionExecution,
    TraceOperationActive,
    TraceOperationNotActive,
    TransactionAttemptActive,
    TransactionCheckpointClosed,
    TransactionCheckpointOrderViolation,
    WrongBlockExecution,

    BalanceOverflow,
    CodeHashMismatch,
    CodeUnavailable,
    InvalidCodeResources,
    InvalidPrecompileOutput,
    InvalidRuntimeResourcesCapacity,
    InvalidWitness,
    NotImplemented,
    SystemCallFailed,
};

pub fn normalize(err: anyerror) Error {
    return switch (err) {
        error.OutOfMemory => error.OutOfMemory,

        error.AccessCapacityTooLarge => error.AccessCapacityTooLarge,
        error.AccountCapacityExceeded => error.AccountCapacityExceeded,
        error.CodeCacheByteCapacityExceeded => error.CodeCacheByteCapacityExceeded,
        error.CodeCacheEntryCapacityExceeded => error.CodeCacheEntryCapacityExceeded,
        error.CreatedContractCapacityExceeded => error.CreatedContractCapacityExceeded,
        error.DeletedAccountCapacityExceeded => error.DeletedAccountCapacityExceeded,
        error.DirtyAccountCapacityExceeded => error.DirtyAccountCapacityExceeded,
        error.FrameCapacityExceeded => error.FrameCapacityExceeded,
        error.FrameIoCapacityExceeded => error.FrameIoCapacityExceeded,
        error.JournalCapacityExceeded => error.JournalCapacityExceeded,
        error.LogCapacityExceeded => error.LogCapacityExceeded,
        error.LogDataCapacityExceeded => error.LogDataCapacityExceeded,
        error.LogTopicCapacityExceeded => error.LogTopicCapacityExceeded,
        error.OriginalStorageCapacityExceeded => error.OriginalStorageCapacityExceeded,
        error.PreparedCodeCapacityExceeded => error.PreparedCodeCapacityExceeded,
        error.ResultOutputCapacityExceeded => error.ResultOutputCapacityExceeded,
        error.SelfdestructCapacityExceeded => error.SelfdestructCapacityExceeded,
        error.StateCapacityTooLarge => error.StateCapacityTooLarge,
        error.StorageOverlayCapacityExceeded => error.StorageOverlayCapacityExceeded,
        error.TraceCapacityExceeded => error.TraceCapacityExceeded,
        error.TraceIndexOverflow => error.TraceIndexOverflow,
        error.TransientStorageCapacityExceeded => error.TransientStorageCapacityExceeded,
        error.TransientStorageCapacityTooLarge => error.TransientStorageCapacityTooLarge,
        error.WarmAccountCapacityExceeded => error.WarmAccountCapacityExceeded,
        error.WarmStorageCapacityExceeded => error.WarmStorageCapacityExceeded,

        error.ActiveAccessState => error.ActiveAccessState,
        error.ActiveCaptureFrames => error.ActiveCaptureFrames,
        error.ActiveCheckpoints => error.ActiveCheckpoints,
        error.ActiveExecutionCheckpoints => error.ActiveExecutionCheckpoints,
        error.ActiveFramesInFrameStore => error.ActiveFramesInFrameStore,
        error.ActiveJournal => error.ActiveJournal,
        error.ActiveLogs => error.ActiveLogs,
        error.ActivePreparedCodeExecution => error.ActivePreparedCodeExecution,
        error.ActiveRuntimeFrames => error.ActiveRuntimeFrames,
        error.ActiveStateOverlay => error.ActiveStateOverlay,
        error.ActiveTransactionScope => error.ActiveTransactionScope,
        error.ActiveTransientStorage => error.ActiveTransientStorage,
        error.BlockExecutionActive => error.BlockExecutionActive,
        error.BlockExecutionFinished => error.BlockExecutionFinished,
        error.CaptureOperationActive => error.CaptureOperationActive,
        error.CaptureOperationNotActive => error.CaptureOperationNotActive,
        error.CheckpointClosed => error.CheckpointClosed,
        error.CheckpointIdExhausted => error.CheckpointIdExhausted,
        error.CheckpointOrderViolation => error.CheckpointOrderViolation,
        error.ExecutedTransactionActive => error.ExecutedTransactionActive,
        error.ExecutionContextMismatch => error.ExecutionContextMismatch,
        error.ExecutionScopeRootMismatch => error.ExecutionScopeRootMismatch,
        error.MissingPreparedCodeExecution => error.MissingPreparedCodeExecution,
        error.MissingTransactionScope => error.MissingTransactionScope,
        error.MissingTxContext => error.MissingTxContext,
        error.NoCurrentTransaction => error.NoCurrentTransaction,
        error.PendingTransactionActive => error.PendingTransactionActive,
        error.RuntimeResourcesLocked => error.RuntimeResourcesLocked,
        error.StaleBlockExecution => error.StaleBlockExecution,
        error.StaleTransactionExecution => error.StaleTransactionExecution,
        error.TraceOperationActive => error.TraceOperationActive,
        error.TraceOperationNotActive => error.TraceOperationNotActive,
        error.TransactionAttemptActive => error.TransactionAttemptActive,
        error.TransactionCheckpointClosed => error.TransactionCheckpointClosed,
        error.TransactionCheckpointOrderViolation => error.TransactionCheckpointOrderViolation,
        error.WrongBlockExecution => error.WrongBlockExecution,

        error.BalanceOverflow => error.BalanceOverflow,
        error.CodeHashMismatch => error.CodeHashMismatch,
        error.CodeUnavailable => error.CodeUnavailable,
        error.InvalidCodeResources => error.InvalidCodeResources,
        error.InvalidPrecompileOutput => error.InvalidPrecompileOutput,
        error.InvalidRuntimeResourcesCapacity => error.InvalidRuntimeResourcesCapacity,
        error.InvalidWitness => error.InvalidWitness,
        error.NotImplemented => error.NotImplemented,
        error.SystemCallFailed => error.SystemCallFailed,
        else => error.InfrastructureFailure,
    };
}

test "normalization preserves bounded resource failures and contains provider errors" {
    const testing = @import("std").testing;
    const bounded_failures = [_]anyerror{
        error.AccessCapacityTooLarge,
        error.AccountCapacityExceeded,
        error.CodeCacheByteCapacityExceeded,
        error.CodeCacheEntryCapacityExceeded,
        error.CreatedContractCapacityExceeded,
        error.DeletedAccountCapacityExceeded,
        error.DirtyAccountCapacityExceeded,
        error.FrameCapacityExceeded,
        error.FrameIoCapacityExceeded,
        error.JournalCapacityExceeded,
        error.LogCapacityExceeded,
        error.LogDataCapacityExceeded,
        error.LogTopicCapacityExceeded,
        error.OriginalStorageCapacityExceeded,
        error.PreparedCodeCapacityExceeded,
        error.ResultOutputCapacityExceeded,
        error.SelfdestructCapacityExceeded,
        error.StateCapacityTooLarge,
        error.StorageOverlayCapacityExceeded,
        error.TraceCapacityExceeded,
        error.TraceIndexOverflow,
        error.TransientStorageCapacityExceeded,
        error.TransientStorageCapacityTooLarge,
        error.WarmAccountCapacityExceeded,
        error.WarmStorageCapacityExceeded,
    };
    for (bounded_failures) |failure| {
        try testing.expectEqualStrings(@errorName(failure), @errorName(normalize(failure)));
    }
    try testing.expectEqual(error.InfrastructureFailure, normalize(error.ProviderSpecificFailure));
}
