//! Generated from consensus-specs v1.7.0-alpha.12 resolved pyspec.
//! Maps preset/fork fixture names to deduplicated schema codecs.
//! Regenerate with scripts/generate-consensus-ssz-schemas.py.

pub const Preset = enum {
    mainnet,
    minimal,
};

pub const Fork = enum {
    phase0,
    altair,
    bellatrix,
    capella,
    deneb,
    electra,
    fulu,
    gloas,
    heze,
};

const phase0_types = @import("phase0.zig");
const altair_types = @import("altair.zig");
const bellatrix_types = @import("bellatrix.zig");
const capella_types = @import("capella.zig");
const deneb_types = @import("deneb.zig");
const electra_types = @import("electra.zig");
const fulu_types = @import("fulu.zig");
const gloas_types = @import("gloas.zig");
const heze_types = @import("heze.zig");

pub const mainnet = struct {
    pub const phase0 = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BeaconBlock", .codec = phase0_types.BeaconBlockPhase0.Ssz },
            .{ .name = "BeaconBlockBody", .codec = phase0_types.BeaconBlockBodyPhase0.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = phase0_types.BeaconStatePhase0Mainnet.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalBatch", .codec = phase0_types.HistoricalBatchPhase0Mainnet.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "PendingAttestation", .codec = phase0_types.PendingAttestation.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = phase0_types.SignedBeaconBlockPhase0.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
        };
    };
    pub const altair = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BeaconBlock", .codec = altair_types.BeaconBlockAltairMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = altair_types.BeaconBlockBodyAltairMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = altair_types.BeaconStateAltairMainnet.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalBatch", .codec = phase0_types.HistoricalBatchPhase0Mainnet.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = altair_types.LightClientBootstrapAltairMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = altair_types.LightClientFinalityUpdateAltairMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = altair_types.LightClientHeaderAltair.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = altair_types.LightClientOptimisticUpdateAltairMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = altair_types.LightClientUpdateAltairMainnet.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = altair_types.SignedBeaconBlockAltairMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
        };
    };
    pub const bellatrix = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BeaconBlock", .codec = bellatrix_types.BeaconBlockBellatrixMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = bellatrix_types.BeaconBlockBodyBellatrixMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = bellatrix_types.BeaconStateBellatrixMainnet.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = bellatrix_types.ExecutionPayloadBellatrix.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = bellatrix_types.ExecutionPayloadHeaderBellatrix.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalBatch", .codec = phase0_types.HistoricalBatchPhase0Mainnet.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = altair_types.LightClientBootstrapAltairMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = altair_types.LightClientFinalityUpdateAltairMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = altair_types.LightClientHeaderAltair.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = altair_types.LightClientOptimisticUpdateAltairMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = altair_types.LightClientUpdateAltairMainnet.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = bellatrix_types.SignedBeaconBlockBellatrixMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
        };
    };
    pub const capella = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = capella_types.BeaconBlockCapellaMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = capella_types.BeaconBlockBodyCapellaMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = capella_types.BeaconStateCapellaMainnet.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = capella_types.ExecutionPayloadCapellaMainnet.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = capella_types.ExecutionPayloadHeaderCapella.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = capella_types.LightClientBootstrapCapellaMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = capella_types.LightClientFinalityUpdateCapellaMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = capella_types.LightClientHeaderCapella.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = capella_types.LightClientOptimisticUpdateCapellaMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = capella_types.LightClientUpdateCapellaMainnet.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = capella_types.SignedBeaconBlockCapellaMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
        };
    };
    pub const deneb = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = deneb_types.BeaconBlockDenebMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = deneb_types.BeaconBlockBodyDenebMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = deneb_types.BeaconStateDenebMainnet.Ssz },
            .{ .name = "BlobIdentifier", .codec = deneb_types.BlobIdentifier.Ssz },
            .{ .name = "BlobSidecar", .codec = deneb_types.BlobSidecar.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = deneb_types.ExecutionPayloadDenebMainnet.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = deneb_types.ExecutionPayloadHeaderDeneb.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = deneb_types.LightClientBootstrapDenebMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = deneb_types.LightClientFinalityUpdateDenebMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = deneb_types.LightClientHeaderDeneb.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = deneb_types.LightClientOptimisticUpdateDenebMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = deneb_types.LightClientUpdateDenebMainnet.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = deneb_types.SignedBeaconBlockDenebMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
        };
    };
    pub const electra = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = electra_types.AggregateAndProofElectraMainnet.Ssz },
            .{ .name = "Attestation", .codec = electra_types.AttestationElectraMainnet.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = electra_types.AttesterSlashingElectraMainnet.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = electra_types.BeaconBlockElectraMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = electra_types.BeaconBlockBodyElectraMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = electra_types.BeaconStateElectraMainnet.Ssz },
            .{ .name = "BlobIdentifier", .codec = deneb_types.BlobIdentifier.Ssz },
            .{ .name = "BlobSidecar", .codec = deneb_types.BlobSidecar.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = deneb_types.ExecutionPayloadDenebMainnet.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = deneb_types.ExecutionPayloadHeaderDeneb.Ssz },
            .{ .name = "ExecutionRequests", .codec = electra_types.ExecutionRequestsElectra.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = electra_types.IndexedAttestationElectraMainnet.Ssz },
            .{ .name = "LightClientBootstrap", .codec = electra_types.LightClientBootstrapElectraMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = electra_types.LightClientFinalityUpdateElectraMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = deneb_types.LightClientHeaderDeneb.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = deneb_types.LightClientOptimisticUpdateDenebMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = electra_types.LightClientUpdateElectraMainnet.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = electra_types.SignedAggregateAndProofElectraMainnet.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = electra_types.SignedBeaconBlockElectraMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
    pub const fulu = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = electra_types.AggregateAndProofElectraMainnet.Ssz },
            .{ .name = "Attestation", .codec = electra_types.AttestationElectraMainnet.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = electra_types.AttesterSlashingElectraMainnet.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = electra_types.BeaconBlockElectraMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = electra_types.BeaconBlockBodyElectraMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = fulu_types.BeaconStateFuluMainnet.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "DataColumnSidecar", .codec = fulu_types.DataColumnSidecarFulu.Ssz },
            .{ .name = "DataColumnsByRootIdentifier", .codec = fulu_types.DataColumnsByRootIdentifier.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = deneb_types.ExecutionPayloadDenebMainnet.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = deneb_types.ExecutionPayloadHeaderDeneb.Ssz },
            .{ .name = "ExecutionRequests", .codec = electra_types.ExecutionRequestsElectra.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = electra_types.IndexedAttestationElectraMainnet.Ssz },
            .{ .name = "LightClientBootstrap", .codec = electra_types.LightClientBootstrapElectraMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = electra_types.LightClientFinalityUpdateElectraMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = deneb_types.LightClientHeaderDeneb.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = deneb_types.LightClientOptimisticUpdateDenebMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = electra_types.LightClientUpdateElectraMainnet.Ssz },
            .{ .name = "MatrixEntry", .codec = fulu_types.MatrixEntry.Ssz },
            .{ .name = "PartialDataColumnGroupID", .codec = fulu_types.PartialDataColumnGroupIDFulu.Ssz },
            .{ .name = "PartialDataColumnHeader", .codec = fulu_types.PartialDataColumnHeader.Ssz },
            .{ .name = "PartialDataColumnPartsMetadata", .codec = fulu_types.PartialDataColumnPartsMetadata.Ssz },
            .{ .name = "PartialDataColumnSidecar", .codec = fulu_types.PartialDataColumnSidecarFulu.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = electra_types.SignedAggregateAndProofElectraMainnet.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = electra_types.SignedBeaconBlockElectraMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
    pub const gloas = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = gloas_types.AggregateAndProofGloasMainnet.Ssz },
            .{ .name = "Attestation", .codec = gloas_types.AttestationGloasMainnet.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = gloas_types.AttesterSlashingGloas.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = gloas_types.BeaconBlockGloasMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = gloas_types.BeaconBlockBodyGloasMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = gloas_types.BeaconStateGloasMainnet.Ssz },
            .{ .name = "Builder", .codec = gloas_types.Builder.Ssz },
            .{ .name = "BuilderDepositRequest", .codec = gloas_types.BuilderDepositRequest.Ssz },
            .{ .name = "BuilderExitRequest", .codec = gloas_types.BuilderExitRequest.Ssz },
            .{ .name = "BuilderPendingPayment", .codec = gloas_types.BuilderPendingPayment.Ssz },
            .{ .name = "BuilderPendingWithdrawal", .codec = gloas_types.BuilderPendingWithdrawal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "DataColumnSidecar", .codec = gloas_types.DataColumnSidecarGloas.Ssz },
            .{ .name = "DataColumnsByRootIdentifier", .codec = fulu_types.DataColumnsByRootIdentifier.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = gloas_types.ExecutionPayloadGloas.Ssz },
            .{ .name = "ExecutionPayloadBid", .codec = gloas_types.ExecutionPayloadBidGloas.Ssz },
            .{ .name = "ExecutionPayloadEnvelope", .codec = gloas_types.ExecutionPayloadEnvelope.Ssz },
            .{ .name = "ExecutionRequests", .codec = gloas_types.ExecutionRequestsGloas.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = gloas_types.IndexedAttestationGloas.Ssz },
            .{ .name = "IndexedPayloadAttestation", .codec = gloas_types.IndexedPayloadAttestationGloasMainnet.Ssz },
            .{ .name = "LightClientBootstrap", .codec = gloas_types.LightClientBootstrapGloasMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = gloas_types.LightClientFinalityUpdateGloasMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = gloas_types.LightClientHeaderGloas.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = gloas_types.LightClientOptimisticUpdateGloasMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = gloas_types.LightClientUpdateGloasMainnet.Ssz },
            .{ .name = "MatrixEntry", .codec = fulu_types.MatrixEntry.Ssz },
            .{ .name = "PartialDataColumnGroupID", .codec = gloas_types.PartialDataColumnGroupIDGloas.Ssz },
            .{ .name = "PartialDataColumnPartsMetadata", .codec = fulu_types.PartialDataColumnPartsMetadata.Ssz },
            .{ .name = "PartialDataColumnSidecar", .codec = gloas_types.PartialDataColumnSidecarGloas.Ssz },
            .{ .name = "PayloadAttestation", .codec = gloas_types.PayloadAttestationGloasMainnet.Ssz },
            .{ .name = "PayloadAttestationData", .codec = gloas_types.PayloadAttestationData.Ssz },
            .{ .name = "PayloadAttestationMessage", .codec = gloas_types.PayloadAttestationMessage.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerPreferences", .codec = gloas_types.ProposerPreferences.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = gloas_types.SignedAggregateAndProofGloasMainnet.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = gloas_types.SignedBeaconBlockGloasMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedExecutionPayloadBid", .codec = gloas_types.SignedExecutionPayloadBidGloas.Ssz },
            .{ .name = "SignedExecutionPayloadEnvelope", .codec = gloas_types.SignedExecutionPayloadEnvelope.Ssz },
            .{ .name = "SignedProposerPreferences", .codec = gloas_types.SignedProposerPreferences.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
    pub const heze = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = gloas_types.AggregateAndProofGloasMainnet.Ssz },
            .{ .name = "Attestation", .codec = gloas_types.AttestationGloasMainnet.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = gloas_types.AttesterSlashingGloas.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = heze_types.BeaconBlockHezeMainnet.Ssz },
            .{ .name = "BeaconBlockBody", .codec = heze_types.BeaconBlockBodyHezeMainnet.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = heze_types.BeaconStateHezeMainnet.Ssz },
            .{ .name = "Builder", .codec = gloas_types.Builder.Ssz },
            .{ .name = "BuilderDepositRequest", .codec = gloas_types.BuilderDepositRequest.Ssz },
            .{ .name = "BuilderExitRequest", .codec = gloas_types.BuilderExitRequest.Ssz },
            .{ .name = "BuilderPendingPayment", .codec = gloas_types.BuilderPendingPayment.Ssz },
            .{ .name = "BuilderPendingWithdrawal", .codec = gloas_types.BuilderPendingWithdrawal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMainnet.Ssz },
            .{ .name = "DataColumnSidecar", .codec = gloas_types.DataColumnSidecarGloas.Ssz },
            .{ .name = "DataColumnsByRootIdentifier", .codec = fulu_types.DataColumnsByRootIdentifier.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = gloas_types.ExecutionPayloadGloas.Ssz },
            .{ .name = "ExecutionPayloadBid", .codec = heze_types.ExecutionPayloadBidHeze.Ssz },
            .{ .name = "ExecutionPayloadEnvelope", .codec = gloas_types.ExecutionPayloadEnvelope.Ssz },
            .{ .name = "ExecutionRequests", .codec = gloas_types.ExecutionRequestsGloas.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "InclusionList", .codec = heze_types.InclusionList.Ssz },
            .{ .name = "IndexedAttestation", .codec = gloas_types.IndexedAttestationGloas.Ssz },
            .{ .name = "IndexedPayloadAttestation", .codec = gloas_types.IndexedPayloadAttestationGloasMainnet.Ssz },
            .{ .name = "LightClientBootstrap", .codec = gloas_types.LightClientBootstrapGloasMainnet.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = gloas_types.LightClientFinalityUpdateGloasMainnet.Ssz },
            .{ .name = "LightClientHeader", .codec = gloas_types.LightClientHeaderGloas.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = gloas_types.LightClientOptimisticUpdateGloasMainnet.Ssz },
            .{ .name = "LightClientUpdate", .codec = gloas_types.LightClientUpdateGloasMainnet.Ssz },
            .{ .name = "MatrixEntry", .codec = fulu_types.MatrixEntry.Ssz },
            .{ .name = "PartialDataColumnGroupID", .codec = gloas_types.PartialDataColumnGroupIDGloas.Ssz },
            .{ .name = "PartialDataColumnPartsMetadata", .codec = fulu_types.PartialDataColumnPartsMetadata.Ssz },
            .{ .name = "PartialDataColumnSidecar", .codec = gloas_types.PartialDataColumnSidecarGloas.Ssz },
            .{ .name = "PayloadAttestation", .codec = gloas_types.PayloadAttestationGloasMainnet.Ssz },
            .{ .name = "PayloadAttestationData", .codec = gloas_types.PayloadAttestationData.Ssz },
            .{ .name = "PayloadAttestationMessage", .codec = gloas_types.PayloadAttestationMessage.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerPreferences", .codec = gloas_types.ProposerPreferences.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = gloas_types.SignedAggregateAndProofGloasMainnet.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = heze_types.SignedBeaconBlockHezeMainnet.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMainnet.Ssz },
            .{ .name = "SignedExecutionPayloadBid", .codec = heze_types.SignedExecutionPayloadBidHeze.Ssz },
            .{ .name = "SignedExecutionPayloadEnvelope", .codec = gloas_types.SignedExecutionPayloadEnvelope.Ssz },
            .{ .name = "SignedInclusionList", .codec = heze_types.SignedInclusionList.Ssz },
            .{ .name = "SignedProposerPreferences", .codec = gloas_types.SignedProposerPreferences.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMainnet.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMainnet.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
};

pub const minimal = struct {
    pub const phase0 = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BeaconBlock", .codec = phase0_types.BeaconBlockPhase0.Ssz },
            .{ .name = "BeaconBlockBody", .codec = phase0_types.BeaconBlockBodyPhase0.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = phase0_types.BeaconStatePhase0Minimal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalBatch", .codec = phase0_types.HistoricalBatchPhase0Minimal.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "PendingAttestation", .codec = phase0_types.PendingAttestation.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = phase0_types.SignedBeaconBlockPhase0.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
        };
    };
    pub const altair = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BeaconBlock", .codec = altair_types.BeaconBlockAltairMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = altair_types.BeaconBlockBodyAltairMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = altair_types.BeaconStateAltairMinimal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalBatch", .codec = phase0_types.HistoricalBatchPhase0Minimal.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = altair_types.LightClientBootstrapAltairMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = altair_types.LightClientFinalityUpdateAltairMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = altair_types.LightClientHeaderAltair.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = altair_types.LightClientOptimisticUpdateAltairMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = altair_types.LightClientUpdateAltairMinimal.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = altair_types.SignedBeaconBlockAltairMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
        };
    };
    pub const bellatrix = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BeaconBlock", .codec = bellatrix_types.BeaconBlockBellatrixMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = bellatrix_types.BeaconBlockBodyBellatrixMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = bellatrix_types.BeaconStateBellatrixMinimal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = bellatrix_types.ExecutionPayloadBellatrix.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = bellatrix_types.ExecutionPayloadHeaderBellatrix.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalBatch", .codec = phase0_types.HistoricalBatchPhase0Minimal.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = altair_types.LightClientBootstrapAltairMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = altair_types.LightClientFinalityUpdateAltairMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = altair_types.LightClientHeaderAltair.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = altair_types.LightClientOptimisticUpdateAltairMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = altair_types.LightClientUpdateAltairMinimal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = bellatrix_types.SignedBeaconBlockBellatrixMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
        };
    };
    pub const capella = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = capella_types.BeaconBlockCapellaMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = capella_types.BeaconBlockBodyCapellaMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = capella_types.BeaconStateCapellaMinimal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = capella_types.ExecutionPayloadCapellaMinimal.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = capella_types.ExecutionPayloadHeaderCapella.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = capella_types.LightClientBootstrapCapellaMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = capella_types.LightClientFinalityUpdateCapellaMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = capella_types.LightClientHeaderCapella.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = capella_types.LightClientOptimisticUpdateCapellaMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = capella_types.LightClientUpdateCapellaMinimal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = capella_types.SignedBeaconBlockCapellaMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
        };
    };
    pub const deneb = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = phase0_types.AggregateAndProofPhase0.Ssz },
            .{ .name = "Attestation", .codec = phase0_types.AttestationPhase0.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = phase0_types.AttesterSlashingPhase0.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = deneb_types.BeaconBlockDenebMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = deneb_types.BeaconBlockBodyDenebMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = deneb_types.BeaconStateDenebMinimal.Ssz },
            .{ .name = "BlobIdentifier", .codec = deneb_types.BlobIdentifier.Ssz },
            .{ .name = "BlobSidecar", .codec = deneb_types.BlobSidecar.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = deneb_types.ExecutionPayloadDenebMinimal.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = deneb_types.ExecutionPayloadHeaderDeneb.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = phase0_types.IndexedAttestationPhase0.Ssz },
            .{ .name = "LightClientBootstrap", .codec = deneb_types.LightClientBootstrapDenebMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = deneb_types.LightClientFinalityUpdateDenebMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = deneb_types.LightClientHeaderDeneb.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = deneb_types.LightClientOptimisticUpdateDenebMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = deneb_types.LightClientUpdateDenebMinimal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = phase0_types.SignedAggregateAndProofPhase0.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = deneb_types.SignedBeaconBlockDenebMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
        };
    };
    pub const electra = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = electra_types.AggregateAndProofElectraMinimal.Ssz },
            .{ .name = "Attestation", .codec = electra_types.AttestationElectraMinimal.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = electra_types.AttesterSlashingElectraMinimal.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = electra_types.BeaconBlockElectraMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = electra_types.BeaconBlockBodyElectraMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = electra_types.BeaconStateElectraMinimal.Ssz },
            .{ .name = "BlobIdentifier", .codec = deneb_types.BlobIdentifier.Ssz },
            .{ .name = "BlobSidecar", .codec = deneb_types.BlobSidecar.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = deneb_types.ExecutionPayloadDenebMinimal.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = deneb_types.ExecutionPayloadHeaderDeneb.Ssz },
            .{ .name = "ExecutionRequests", .codec = electra_types.ExecutionRequestsElectra.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = electra_types.IndexedAttestationElectraMinimal.Ssz },
            .{ .name = "LightClientBootstrap", .codec = electra_types.LightClientBootstrapElectraMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = electra_types.LightClientFinalityUpdateElectraMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = deneb_types.LightClientHeaderDeneb.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = deneb_types.LightClientOptimisticUpdateDenebMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = electra_types.LightClientUpdateElectraMinimal.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = electra_types.SignedAggregateAndProofElectraMinimal.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = electra_types.SignedBeaconBlockElectraMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
    pub const fulu = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = electra_types.AggregateAndProofElectraMinimal.Ssz },
            .{ .name = "Attestation", .codec = electra_types.AttestationElectraMinimal.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = electra_types.AttesterSlashingElectraMinimal.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = electra_types.BeaconBlockElectraMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = electra_types.BeaconBlockBodyElectraMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = fulu_types.BeaconStateFuluMinimal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "DataColumnSidecar", .codec = fulu_types.DataColumnSidecarFulu.Ssz },
            .{ .name = "DataColumnsByRootIdentifier", .codec = fulu_types.DataColumnsByRootIdentifier.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = deneb_types.ExecutionPayloadDenebMinimal.Ssz },
            .{ .name = "ExecutionPayloadHeader", .codec = deneb_types.ExecutionPayloadHeaderDeneb.Ssz },
            .{ .name = "ExecutionRequests", .codec = electra_types.ExecutionRequestsElectra.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = electra_types.IndexedAttestationElectraMinimal.Ssz },
            .{ .name = "LightClientBootstrap", .codec = electra_types.LightClientBootstrapElectraMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = electra_types.LightClientFinalityUpdateElectraMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = deneb_types.LightClientHeaderDeneb.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = deneb_types.LightClientOptimisticUpdateDenebMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = electra_types.LightClientUpdateElectraMinimal.Ssz },
            .{ .name = "MatrixEntry", .codec = fulu_types.MatrixEntry.Ssz },
            .{ .name = "PartialDataColumnGroupID", .codec = fulu_types.PartialDataColumnGroupIDFulu.Ssz },
            .{ .name = "PartialDataColumnHeader", .codec = fulu_types.PartialDataColumnHeader.Ssz },
            .{ .name = "PartialDataColumnPartsMetadata", .codec = fulu_types.PartialDataColumnPartsMetadata.Ssz },
            .{ .name = "PartialDataColumnSidecar", .codec = fulu_types.PartialDataColumnSidecarFulu.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = electra_types.SignedAggregateAndProofElectraMinimal.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = electra_types.SignedBeaconBlockElectraMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
    pub const gloas = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = gloas_types.AggregateAndProofGloasMinimal.Ssz },
            .{ .name = "Attestation", .codec = gloas_types.AttestationGloasMinimal.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = gloas_types.AttesterSlashingGloas.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = gloas_types.BeaconBlockGloasMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = gloas_types.BeaconBlockBodyGloasMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = gloas_types.BeaconStateGloasMinimal.Ssz },
            .{ .name = "Builder", .codec = gloas_types.Builder.Ssz },
            .{ .name = "BuilderDepositRequest", .codec = gloas_types.BuilderDepositRequest.Ssz },
            .{ .name = "BuilderExitRequest", .codec = gloas_types.BuilderExitRequest.Ssz },
            .{ .name = "BuilderPendingPayment", .codec = gloas_types.BuilderPendingPayment.Ssz },
            .{ .name = "BuilderPendingWithdrawal", .codec = gloas_types.BuilderPendingWithdrawal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "DataColumnSidecar", .codec = gloas_types.DataColumnSidecarGloas.Ssz },
            .{ .name = "DataColumnsByRootIdentifier", .codec = fulu_types.DataColumnsByRootIdentifier.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = gloas_types.ExecutionPayloadGloas.Ssz },
            .{ .name = "ExecutionPayloadBid", .codec = gloas_types.ExecutionPayloadBidGloas.Ssz },
            .{ .name = "ExecutionPayloadEnvelope", .codec = gloas_types.ExecutionPayloadEnvelope.Ssz },
            .{ .name = "ExecutionRequests", .codec = gloas_types.ExecutionRequestsGloas.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "IndexedAttestation", .codec = gloas_types.IndexedAttestationGloas.Ssz },
            .{ .name = "IndexedPayloadAttestation", .codec = gloas_types.IndexedPayloadAttestationGloasMinimal.Ssz },
            .{ .name = "LightClientBootstrap", .codec = gloas_types.LightClientBootstrapGloasMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = gloas_types.LightClientFinalityUpdateGloasMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = gloas_types.LightClientHeaderGloas.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = gloas_types.LightClientOptimisticUpdateGloasMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = gloas_types.LightClientUpdateGloasMinimal.Ssz },
            .{ .name = "MatrixEntry", .codec = fulu_types.MatrixEntry.Ssz },
            .{ .name = "PartialDataColumnGroupID", .codec = gloas_types.PartialDataColumnGroupIDGloas.Ssz },
            .{ .name = "PartialDataColumnPartsMetadata", .codec = fulu_types.PartialDataColumnPartsMetadata.Ssz },
            .{ .name = "PartialDataColumnSidecar", .codec = gloas_types.PartialDataColumnSidecarGloas.Ssz },
            .{ .name = "PayloadAttestation", .codec = gloas_types.PayloadAttestationGloasMinimal.Ssz },
            .{ .name = "PayloadAttestationData", .codec = gloas_types.PayloadAttestationData.Ssz },
            .{ .name = "PayloadAttestationMessage", .codec = gloas_types.PayloadAttestationMessage.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerPreferences", .codec = gloas_types.ProposerPreferences.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = gloas_types.SignedAggregateAndProofGloasMinimal.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = gloas_types.SignedBeaconBlockGloasMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedExecutionPayloadBid", .codec = gloas_types.SignedExecutionPayloadBidGloas.Ssz },
            .{ .name = "SignedExecutionPayloadEnvelope", .codec = gloas_types.SignedExecutionPayloadEnvelope.Ssz },
            .{ .name = "SignedProposerPreferences", .codec = gloas_types.SignedProposerPreferences.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
    pub const heze = struct {
        pub const handlers = .{
            .{ .name = "AggregateAndProof", .codec = gloas_types.AggregateAndProofGloasMinimal.Ssz },
            .{ .name = "Attestation", .codec = gloas_types.AttestationGloasMinimal.Ssz },
            .{ .name = "AttestationData", .codec = phase0_types.AttestationData.Ssz },
            .{ .name = "AttesterSlashing", .codec = gloas_types.AttesterSlashingGloas.Ssz },
            .{ .name = "BLSToExecutionChange", .codec = capella_types.BLSToExecutionChange.Ssz },
            .{ .name = "BeaconBlock", .codec = heze_types.BeaconBlockHezeMinimal.Ssz },
            .{ .name = "BeaconBlockBody", .codec = heze_types.BeaconBlockBodyHezeMinimal.Ssz },
            .{ .name = "BeaconBlockHeader", .codec = phase0_types.BeaconBlockHeader.Ssz },
            .{ .name = "BeaconState", .codec = heze_types.BeaconStateHezeMinimal.Ssz },
            .{ .name = "Builder", .codec = gloas_types.Builder.Ssz },
            .{ .name = "BuilderDepositRequest", .codec = gloas_types.BuilderDepositRequest.Ssz },
            .{ .name = "BuilderExitRequest", .codec = gloas_types.BuilderExitRequest.Ssz },
            .{ .name = "BuilderPendingPayment", .codec = gloas_types.BuilderPendingPayment.Ssz },
            .{ .name = "BuilderPendingWithdrawal", .codec = gloas_types.BuilderPendingWithdrawal.Ssz },
            .{ .name = "Checkpoint", .codec = phase0_types.Checkpoint.Ssz },
            .{ .name = "ConsolidationRequest", .codec = electra_types.ConsolidationRequest.Ssz },
            .{ .name = "ContributionAndProof", .codec = altair_types.ContributionAndProofAltairMinimal.Ssz },
            .{ .name = "DataColumnSidecar", .codec = gloas_types.DataColumnSidecarGloas.Ssz },
            .{ .name = "DataColumnsByRootIdentifier", .codec = fulu_types.DataColumnsByRootIdentifier.Ssz },
            .{ .name = "Deposit", .codec = phase0_types.Deposit.Ssz },
            .{ .name = "DepositData", .codec = phase0_types.DepositData.Ssz },
            .{ .name = "DepositMessage", .codec = phase0_types.DepositMessage.Ssz },
            .{ .name = "DepositRequest", .codec = electra_types.DepositRequest.Ssz },
            .{ .name = "Eth1Block", .codec = phase0_types.Eth1Block.Ssz },
            .{ .name = "Eth1Data", .codec = phase0_types.Eth1Data.Ssz },
            .{ .name = "ExecutionPayload", .codec = gloas_types.ExecutionPayloadGloas.Ssz },
            .{ .name = "ExecutionPayloadBid", .codec = heze_types.ExecutionPayloadBidHeze.Ssz },
            .{ .name = "ExecutionPayloadEnvelope", .codec = gloas_types.ExecutionPayloadEnvelope.Ssz },
            .{ .name = "ExecutionRequests", .codec = gloas_types.ExecutionRequestsGloas.Ssz },
            .{ .name = "Fork", .codec = phase0_types.Fork.Ssz },
            .{ .name = "ForkData", .codec = phase0_types.ForkData.Ssz },
            .{ .name = "HistoricalSummary", .codec = capella_types.HistoricalSummary.Ssz },
            .{ .name = "InclusionList", .codec = heze_types.InclusionList.Ssz },
            .{ .name = "IndexedAttestation", .codec = gloas_types.IndexedAttestationGloas.Ssz },
            .{ .name = "IndexedPayloadAttestation", .codec = gloas_types.IndexedPayloadAttestationGloasMinimal.Ssz },
            .{ .name = "LightClientBootstrap", .codec = gloas_types.LightClientBootstrapGloasMinimal.Ssz },
            .{ .name = "LightClientFinalityUpdate", .codec = gloas_types.LightClientFinalityUpdateGloasMinimal.Ssz },
            .{ .name = "LightClientHeader", .codec = gloas_types.LightClientHeaderGloas.Ssz },
            .{ .name = "LightClientOptimisticUpdate", .codec = gloas_types.LightClientOptimisticUpdateGloasMinimal.Ssz },
            .{ .name = "LightClientUpdate", .codec = gloas_types.LightClientUpdateGloasMinimal.Ssz },
            .{ .name = "MatrixEntry", .codec = fulu_types.MatrixEntry.Ssz },
            .{ .name = "PartialDataColumnGroupID", .codec = gloas_types.PartialDataColumnGroupIDGloas.Ssz },
            .{ .name = "PartialDataColumnPartsMetadata", .codec = fulu_types.PartialDataColumnPartsMetadata.Ssz },
            .{ .name = "PartialDataColumnSidecar", .codec = gloas_types.PartialDataColumnSidecarGloas.Ssz },
            .{ .name = "PayloadAttestation", .codec = gloas_types.PayloadAttestationGloasMinimal.Ssz },
            .{ .name = "PayloadAttestationData", .codec = gloas_types.PayloadAttestationData.Ssz },
            .{ .name = "PayloadAttestationMessage", .codec = gloas_types.PayloadAttestationMessage.Ssz },
            .{ .name = "PendingConsolidation", .codec = electra_types.PendingConsolidation.Ssz },
            .{ .name = "PendingDeposit", .codec = electra_types.PendingDeposit.Ssz },
            .{ .name = "PendingPartialWithdrawal", .codec = electra_types.PendingPartialWithdrawal.Ssz },
            .{ .name = "PowBlock", .codec = bellatrix_types.PowBlock.Ssz },
            .{ .name = "ProposerPreferences", .codec = gloas_types.ProposerPreferences.Ssz },
            .{ .name = "ProposerSlashing", .codec = phase0_types.ProposerSlashing.Ssz },
            .{ .name = "SignedAggregateAndProof", .codec = gloas_types.SignedAggregateAndProofGloasMinimal.Ssz },
            .{ .name = "SignedBLSToExecutionChange", .codec = capella_types.SignedBLSToExecutionChange.Ssz },
            .{ .name = "SignedBeaconBlock", .codec = heze_types.SignedBeaconBlockHezeMinimal.Ssz },
            .{ .name = "SignedBeaconBlockHeader", .codec = phase0_types.SignedBeaconBlockHeader.Ssz },
            .{ .name = "SignedContributionAndProof", .codec = altair_types.SignedContributionAndProofAltairMinimal.Ssz },
            .{ .name = "SignedExecutionPayloadBid", .codec = heze_types.SignedExecutionPayloadBidHeze.Ssz },
            .{ .name = "SignedExecutionPayloadEnvelope", .codec = gloas_types.SignedExecutionPayloadEnvelope.Ssz },
            .{ .name = "SignedInclusionList", .codec = heze_types.SignedInclusionList.Ssz },
            .{ .name = "SignedProposerPreferences", .codec = gloas_types.SignedProposerPreferences.Ssz },
            .{ .name = "SignedVoluntaryExit", .codec = phase0_types.SignedVoluntaryExit.Ssz },
            .{ .name = "SigningData", .codec = phase0_types.SigningData.Ssz },
            .{ .name = "SingleAttestation", .codec = electra_types.SingleAttestation.Ssz },
            .{ .name = "SyncAggregate", .codec = altair_types.SyncAggregateAltairMinimal.Ssz },
            .{ .name = "SyncAggregatorSelectionData", .codec = altair_types.SyncAggregatorSelectionData.Ssz },
            .{ .name = "SyncCommittee", .codec = altair_types.SyncCommitteeAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeContribution", .codec = altair_types.SyncCommitteeContributionAltairMinimal.Ssz },
            .{ .name = "SyncCommitteeMessage", .codec = altair_types.SyncCommitteeMessage.Ssz },
            .{ .name = "Validator", .codec = phase0_types.Validator.Ssz },
            .{ .name = "VoluntaryExit", .codec = phase0_types.VoluntaryExit.Ssz },
            .{ .name = "Withdrawal", .codec = capella_types.Withdrawal.Ssz },
            .{ .name = "WithdrawalRequest", .codec = electra_types.WithdrawalRequest.Ssz },
        };
    };
};
